version: '3'
services:
  web:
    image: docker.io/bitnami/laravel:10
    container_name: media-server-web
    ports:
      - "8011:8000"
    volumes:
      - '.:/app'
    depends_on:
      - mysql
    networks:
      - commonnet
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=home_media_2
      - DB_USERNAME=root
      - DB_PASSWORD=Password2000!

  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password2000!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - .:/applicaiton
    networks:
      - commonnet


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Password2000!
    depends_on:
      - mysql
    networks:
      - commonnet

volumes:
  mysql_data:

networks:
  commonnet:
    name: commonnet
    driver: bridge
